# =============================================================================
# Prometheus Configuration for Alert Bot Project
# =============================================================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'alert-bot'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules/*.yml"

# Scrape configuration
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # API Gateway Service
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: api-gateway:3000
      - target_label: service
        replacement: api-gateway

  # Subscription Service
  - job_name: 'subscription-service'
    static_configs:
      - targets: ['subscription-service:3001']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    relabel_configs:
      - target_label: service
        replacement: subscription-service

  # Alert Engine Service
  - job_name: 'alert-engine'
    static_configs:
      - targets: ['alert-engine:3002']
    scrape_interval: 10s  # More frequent for alert engine
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    relabel_configs:
      - target_label: service
        replacement: alert-engine

  # Telegram Service
  - job_name: 'telegram-service'
    static_configs:
      - targets: ['telegram-service:3003']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    relabel_configs:
      - target_label: service
        replacement: telegram-service

  # MongoDB Exporter
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s
    relabel_configs:
      - target_label: service
        replacement: mongodb

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s
    relabel_configs:
      - target_label: service
        replacement: redis

  # Node Exporter (System metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s
    relabel_configs:
      - target_label: service
        replacement: system

  # Nginx Exporter
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s
    relabel_configs:
      - target_label: service
        replacement: nginx

  # cAdvisor (Container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s
    relabel_configs:
      - target_label: service
        replacement: containers

  # Custom application metrics
  - job_name: 'custom-metrics'
    static_configs:
      - targets: 
        - 'api-gateway:3000'
        - 'subscription-service:3001'
        - 'alert-engine:3002'
        - 'telegram-service:3003'
    scrape_interval: 30s
    metrics_path: /custom-metrics
    scrape_timeout: 10s
    honor_labels: true

  # Health check endpoints
  - job_name: 'health-checks'
    static_configs:
      - targets:
        - 'api-gateway:3000'
        - 'subscription-service:3001'
        - 'alert-engine:3002'
        - 'telegram-service:3003'
    scrape_interval: 10s
    metrics_path: /health
    scrape_timeout: 5s
    honor_labels: true
    relabel_configs:
      - target_label: check_type
        replacement: health

  # External API monitoring (if endpoints are available)
  - job_name: 'external-apis'
    static_configs:
      - targets:
        - 'api.binance.com:443'
        - 'api.coingecko.com:443'
    scrape_interval: 60s
    metrics_path: /ping
    scheme: https
    scrape_timeout: 30s
    honor_labels: true
    relabel_configs:
      - target_label: service
        replacement: external-api
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'up'
        target_label: __name__
        replacement: 'external_api_up'

# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint/api/v1/write"
#     basic_auth:
#       username: "username"
#       password: "password"
#     write_relabel_configs:
#       - source_labels: [__name__]
#         regex: 'go_.*'
#         action: drop

# Remote read configuration
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint/api/v1/read"
#     basic_auth:
#       username: "username"
#       password: "password"

# Storage configuration
storage:
  tsdb:
    retention.time: 15d
    retention.size: 10GB
    wal-compression: true

# Feature flags
# runtime:
#   gogc: 75